#设置Tomcat端口，默认8080
server:
 port: 8083

spring:
#数据库配置
 datasource:
  url: jdbc:mysql://192.168.59.100:3306/stock?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
  username: xgoing
  password: 123456
  driverClassName: com.mysql.jdbc.Driver
  type: com.alibaba.druid.pool.DruidDataSource
  initialSize: 5  
  minIdle: 5  
  maxActive: 20  
  maxWait: 60000  
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 1 FROM DUAL
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20
  filters: stat,wall,log4j
  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#配置kafka
kafka:
 bootstrap-servers: 192.168.59.100:9092,192.168.59.100:9093
 producer:
  retries: 0
  batch-size: 16384
  buffer-memory: 33554432
  key-serializer: org.apache.kafka.common.serialization.StringSerializer
  value-serializer: org.apache.kafka.common.serialization.StringSerializer
 consumer:
  group-id: 0
  auto-offset-reset: latest
  enable-auto-commit: true
  auto-commit-interval: 20000
  concurrency: 10
  enable.auto.commit: true
  key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
redis:
 host: 192.168.59.100
 port: 6379
#配置.xml文件路径
mybatis:
 mapperLocations: classpath:mapper/*.xml
#日志
logging:
  level:
   com.xgoing: DEBUG




